
#pragma once

#include "operations.h"

struct opcode {
  Operations op;
  AddrMode mode;

  bool operator==(const opcode& other) const {
    return op == other.op && mode == other.mode;
  }

  bool operator!=(const opcode& other) const {
    return !(*this == other);
  }
};

opcode opcodes[] = {
  { ADC, Immediate0 },
  { AND, Immediate0 }, // same as LDA #0
  { CMP, Immediate0 },
  { CPX, Immediate0 },
  { CPY, Immediate0 },
  { EOR, Immediate0 }, // same as ORA #0
  { LDA, Immediate0 },
  { LDX, Immediate0 },
  { LDY, Immediate0 },
  { ORA, Immediate0 },
  { SBC, Immediate0 },

  { ADC, Immediate1 },
  { AND, Immediate1 },
  { CMP, Immediate1 },
  { CPX, Immediate1 },
  { CPY, Immediate1 },
  { EOR, Immediate1 },
  { LDA, Immediate1 },
  { LDX, Immediate1 },
  { LDY, Immediate1 },
  { ORA, Immediate1 },
  { SBC, Immediate1 },

  { ADC, ImmediateC0 },
  { AND, ImmediateC0 },
  { CMP, ImmediateC0 },
  { CPX, ImmediateC0 },
  { CPY, ImmediateC0 },
  { EOR, ImmediateC0 },
  { LDA, ImmediateC0 },
  { LDX, ImmediateC0 },
  { LDY, ImmediateC0 },
  { ORA, ImmediateC0 },
  { SBC, ImmediateC0 },

  { ADC, ImmediateC1 },
  { AND, ImmediateC1 },
  { CMP, ImmediateC1 },
  { CPX, ImmediateC1 },
  { CPY, ImmediateC1 },
  { EOR, ImmediateC1 },
  { LDA, ImmediateC1 },
  { LDX, ImmediateC1 },
  { LDY, ImmediateC1 },
  { ORA, ImmediateC1 },
  { SBC, ImmediateC1 },

  { ADC, ImmediateC0Plus1 },
  { AND, ImmediateC0Plus1 },
  { CMP, ImmediateC0Plus1 },
  { CPX, ImmediateC0Plus1 },
  { CPY, ImmediateC0Plus1 },
  { EOR, ImmediateC0Plus1 },
  { LDA, ImmediateC0Plus1 },
  { LDX, ImmediateC0Plus1 },
  { LDY, ImmediateC0Plus1 },
  { ORA, ImmediateC0Plus1 },
  { SBC, ImmediateC0Plus1 },

  { ADC, ImmediateC1Plus1 },
  { AND, ImmediateC1Plus1 },
  { CMP, ImmediateC1Plus1 },
  { CPX, ImmediateC1Plus1 },
  { CPY, ImmediateC1Plus1 },
  { EOR, ImmediateC1Plus1 },
  { LDA, ImmediateC1Plus1 },
  { LDX, ImmediateC1Plus1 },
  { LDY, ImmediateC1Plus1 },
  { ORA, ImmediateC1Plus1 },
  { SBC, ImmediateC1Plus1 },

  { ADC, ImmediateC0PlusC1 },
  { AND, ImmediateC0PlusC1 },
  { CMP, ImmediateC0PlusC1 },
  { CPX, ImmediateC0PlusC1 },
  { CPY, ImmediateC0PlusC1 },
  { EOR, ImmediateC0PlusC1 },
  { LDA, ImmediateC0PlusC1 },
  { LDX, ImmediateC0PlusC1 },
  { LDY, ImmediateC0PlusC1 },
  { ORA, ImmediateC0PlusC1 },
  { SBC, ImmediateC0PlusC1 },

  { ADC, ZeroPage0 },
  { AND, ZeroPage0 },
  { ASL, ZeroPage0 },
  { BIT, ZeroPage0 },
  { CMP, ZeroPage0 },
  { CPX, ZeroPage0 },
  { CPY, ZeroPage0 },
  { DEC, ZeroPage0 },
  { EOR, ZeroPage0 },
  { INC, ZeroPage0 },
  { LDA, ZeroPage0 },
  { LDX, ZeroPage0 },
  { LDY, ZeroPage0 },
  { LSR, ZeroPage0 },
  { ORA, ZeroPage0 },
  { ROL, ZeroPage0 },
  { ROR, ZeroPage0 },
  { SBC, ZeroPage0 },
  { STA, ZeroPage0 },
  { STX, ZeroPage0 },
  { STY, ZeroPage0 },

  { ADC, ZeroPage1 },
  { AND, ZeroPage1 },
  { ASL, ZeroPage1 },
  { BIT, ZeroPage1 },
  { CMP, ZeroPage1 },
  { CPX, ZeroPage1 },
  { CPY, ZeroPage1 },
  { DEC, ZeroPage1 },
  { EOR, ZeroPage1 },
  { INC, ZeroPage1 },
  { LDA, ZeroPage1 },
  { LDX, ZeroPage1 },
  { LDY, ZeroPage1 },
  { LSR, ZeroPage1 },
  { ORA, ZeroPage1 },
  { ROL, ZeroPage1 },
  { ROR, ZeroPage1 },
  { SBC, ZeroPage1 },
  { STA, ZeroPage1 },
  { STX, ZeroPage1 },
  { STY, ZeroPage1 },

  { ADC, ZeroPage2 },
  { AND, ZeroPage2 },
  { ASL, ZeroPage2 },
  { BIT, ZeroPage2 },
  { CMP, ZeroPage2 },
  { CPX, ZeroPage2 },
  { CPY, ZeroPage2 },
  { DEC, ZeroPage2 },
  { EOR, ZeroPage2 },
  { INC, ZeroPage2 },
  { LDA, ZeroPage2 },
  { LDX, ZeroPage2 },
  { LDY, ZeroPage2 },
  { LSR, ZeroPage2 },
  { ORA, ZeroPage2 },
  { ROL, ZeroPage2 },
  { ROR, ZeroPage2 },
  { SBC, ZeroPage2 },
  { STA, ZeroPage2 },
  { STX, ZeroPage2 },
  { STY, ZeroPage2 },

  { ADC, ZeroPage3 },
  { AND, ZeroPage3 },
  { ASL, ZeroPage3 },
  { BIT, ZeroPage3 },
  { CMP, ZeroPage3 },
  { CPX, ZeroPage3 },
  { CPY, ZeroPage3 },
  { DEC, ZeroPage3 },
  { EOR, ZeroPage3 },
  { INC, ZeroPage3 },
  { LDA, ZeroPage3 },
  { LDX, ZeroPage3 },
  { LDY, ZeroPage3 },
  { LSR, ZeroPage3 },
  { ORA, ZeroPage3 },
  { ROL, ZeroPage3 },
  { ROR, ZeroPage3 },
  { SBC, ZeroPage3 },
  { STA, ZeroPage3 },
  { STX, ZeroPage3 },
  { STY, ZeroPage3 },

  { ADC, ZeroPageX0 },
  { AND, ZeroPageX0 },
  { ASL, ZeroPageX0 },
  { CMP, ZeroPageX0 },
  { DEC, ZeroPageX0 },
  { EOR, ZeroPageX0 },
  { INC, ZeroPageX0 },
  { LDA, ZeroPageX0 },
  { LDY, ZeroPageX0 },
  { LSR, ZeroPageX0 },
  { ORA, ZeroPageX0 },
  { ROL, ZeroPageX0 },
  { ROR, ZeroPageX0 },
  { SBC, ZeroPageX0 },
  { STA, ZeroPageX0 },
  { STY, ZeroPageX0 },

  { ADC, ZeroPageX1 },
  { AND, ZeroPageX1 },
  { ASL, ZeroPageX1 },
  { CMP, ZeroPageX1 },
  { DEC, ZeroPageX1 },
  { EOR, ZeroPageX1 },
  { INC, ZeroPageX1 },
  { LDA, ZeroPageX1 },
  { LDY, ZeroPageX1 },
  { LSR, ZeroPageX1 },
  { ORA, ZeroPageX1 },
  { ROL, ZeroPageX1 },
  { ROR, ZeroPageX1 },
  { SBC, ZeroPageX1 },
  { STA, ZeroPageX1 },
  { STY, ZeroPageX1 },

  { ADC, ZeroPageX2 },
  { AND, ZeroPageX2 },
  { ASL, ZeroPageX2 },
  { CMP, ZeroPageX2 },
  { DEC, ZeroPageX2 },
  { EOR, ZeroPageX2 },
  { INC, ZeroPageX2 },
  { LDA, ZeroPageX2 },
  { LDY, ZeroPageX2 },
  { LSR, ZeroPageX2 },
  { ORA, ZeroPageX2 },
  { ROL, ZeroPageX2 },
  { ROR, ZeroPageX2 },
  { SBC, ZeroPageX2 },
  { STA, ZeroPageX2 },
  { STY, ZeroPageX2 },

  { ADC, ZeroPageX3 },
  { AND, ZeroPageX3 },
  { ASL, ZeroPageX3 },
  { CMP, ZeroPageX3 },
  { DEC, ZeroPageX3 },
  { EOR, ZeroPageX3 },
  { INC, ZeroPageX3 },
  { LDA, ZeroPageX3 },
  { LDY, ZeroPageX3 },
  { LSR, ZeroPageX3 },
  { ORA, ZeroPageX3 },
  { ROL, ZeroPageX3 },
  { ROR, ZeroPageX3 },
  { SBC, ZeroPageX3 },
  { STA, ZeroPageX3 },
  { STY, ZeroPageX3 },

  { LDX, ZeroPageY0 },
  { STX, ZeroPageY0 },
  { LDX, ZeroPageY1 },
  { STX, ZeroPageY1 },
  { LDX, ZeroPageY2 },
  { STX, ZeroPageY2 },
  { LDX, ZeroPageY3 },
  { STX, ZeroPageY3 },

  { ADC, Absolute0 },
  { AND, Absolute0 },
  { ASL, Absolute0 },
  { BIT, Absolute0 },
  { CMP, Absolute0 },
  { CPX, Absolute0 },
  { CPY, Absolute0 },
  { DEC, Absolute0 },
  { EOR, Absolute0 },
  { INC, Absolute0 },
  { JMP, Absolute0 },
  { LDA, Absolute0 },
  { LDX, Absolute0 },
  { LDY, Absolute0 },
  { LSR, Absolute0 },
  { ORA, Absolute0 },
  { ROL, Absolute0 },
  { ROR, Absolute0 },
  { SBC, Absolute0 },
  { STA, Absolute0 },
  { STX, Absolute0 },
  { STY, Absolute0 },

  { ADC, Absolute1 },
  { AND, Absolute1 },
  { ASL, Absolute1 },
  { BIT, Absolute1 },
  { CMP, Absolute1 },
  { CPX, Absolute1 },
  { CPY, Absolute1 },
  { DEC, Absolute1 },
  { EOR, Absolute1 },
  { INC, Absolute1 },
  { JMP, Absolute1 },
  { LDA, Absolute1 },
  { LDX, Absolute1 },
  { LDY, Absolute1 },
  { LSR, Absolute1 },
  { ORA, Absolute1 },
  { ROL, Absolute1 },
  { ROR, Absolute1 },
  { SBC, Absolute1 },
  { STA, Absolute1 },
  { STX, Absolute1 },
  { STY, Absolute1 },

  { ADC, Absolute2 },
  { AND, Absolute2 },
  { ASL, Absolute2 },
  { BIT, Absolute2 },
  { CMP, Absolute2 },
  { CPX, Absolute2 },
  { CPY, Absolute2 },
  { DEC, Absolute2 },
  { EOR, Absolute2 },
  { INC, Absolute2 },
  { JMP, Absolute2 },
  { LDA, Absolute2 },
  { LDX, Absolute2 },
  { LDY, Absolute2 },
  { LSR, Absolute2 },
  { ORA, Absolute2 },
  { ROL, Absolute2 },
  { ROR, Absolute2 },
  { SBC, Absolute2 },
  { STA, Absolute2 },
  { STX, Absolute2 },
  { STY, Absolute2 },

  { ADC, AbsoluteX0 },
  { AND, AbsoluteX0 },
  { ASL, AbsoluteX0 },
  { CMP, AbsoluteX0 },
  { DEC, AbsoluteX0 },
  { EOR, AbsoluteX0 },
  { INC, AbsoluteX0 },
  { LDA, AbsoluteX0 },
  { LDY, AbsoluteX0 },
  { LSR, AbsoluteX0 },
  { ORA, AbsoluteX0 },
  { ROL, AbsoluteX0 },
  { ROR, AbsoluteX0 },
  { SBC, AbsoluteX0 },
  { STA, AbsoluteX0 },

  { ADC, AbsoluteX1 },
  { AND, AbsoluteX1 },
  { ASL, AbsoluteX1 },
  { CMP, AbsoluteX1 },
  { DEC, AbsoluteX1 },
  { EOR, AbsoluteX1 },
  { INC, AbsoluteX1 },
  { LDA, AbsoluteX1 },
  { LDY, AbsoluteX1 },
  { LSR, AbsoluteX1 },
  { ORA, AbsoluteX1 },
  { ROL, AbsoluteX1 },
  { ROR, AbsoluteX1 },
  { SBC, AbsoluteX1 },
  { STA, AbsoluteX1 },

  { ADC, AbsoluteX2 },
  { AND, AbsoluteX2 },
  { ASL, AbsoluteX2 },
  { CMP, AbsoluteX2 },
  { DEC, AbsoluteX2 },
  { EOR, AbsoluteX2 },
  { INC, AbsoluteX2 },
  { LDA, AbsoluteX2 },
  { LDY, AbsoluteX2 },
  { LSR, AbsoluteX2 },
  { ORA, AbsoluteX2 },
  { ROL, AbsoluteX2 },
  { ROR, AbsoluteX2 },
  { SBC, AbsoluteX2 },
  { STA, AbsoluteX2 },

  { ADC, AbsoluteY0 },
  { AND, AbsoluteY0 },
  { EOR, AbsoluteY0 },
  { LDA, AbsoluteY0 },
  { LDX, AbsoluteY0 },
  { ORA, AbsoluteY0 },
  { SBC, AbsoluteY0 },
  { STA, AbsoluteY0 },

  { ADC, AbsoluteY1 },
  { AND, AbsoluteY1 },
  { EOR, AbsoluteY1 },
  { LDA, AbsoluteY1 },
  { LDX, AbsoluteY1 },
  { ORA, AbsoluteY1 },
  { SBC, AbsoluteY1 },
  { STA, AbsoluteY1 },

  { ADC, AbsoluteY2 },
  { AND, AbsoluteY2 },
  { EOR, AbsoluteY2 },
  { LDA, AbsoluteY2 },
  { LDX, AbsoluteY2 },
  { ORA, AbsoluteY2 },
  { SBC, AbsoluteY2 },
  { STA, AbsoluteY2 },

  { ADC, IndirectX0 },
  { AND, IndirectX0 },
  { CMP, IndirectX0 },
  { EOR, IndirectX0 },
  { LDA, IndirectX0 },
  { ORA, IndirectX0 },
  { SBC, IndirectX0 },
  { STA, IndirectX0 },

  { ADC, IndirectX1 },
  { AND, IndirectX1 },
  { CMP, IndirectX1 },
  { EOR, IndirectX1 },
  { LDA, IndirectX1 },
  { ORA, IndirectX1 },
  { SBC, IndirectX1 },
  { STA, IndirectX1 },

  { ADC, IndirectX2 },
  { AND, IndirectX2 },
  { CMP, IndirectX2 },
  { EOR, IndirectX2 },
  { LDA, IndirectX2 },
  { ORA, IndirectX2 },
  { SBC, IndirectX2 },
  { STA, IndirectX2 },

  { ADC, IndirectX3 },
  { AND, IndirectX3 },
  { CMP, IndirectX3 },
  { EOR, IndirectX3 },
  { LDA, IndirectX3 },
  { ORA, IndirectX3 },
  { SBC, IndirectX3 },
  { STA, IndirectX3 },

  { ADC, IndirectY0 },
  { AND, IndirectY0 },
  { CMP, IndirectY0 },
  { EOR, IndirectY0 },
  { LDA, IndirectY0 },
  { ORA, IndirectY0 },
  { SBC, IndirectY0 },
  { STA, IndirectY0 },

  { ADC, IndirectY1 },
  { AND, IndirectY1 },
  { CMP, IndirectY1 },
  { EOR, IndirectY1 },
  { LDA, IndirectY1 },
  { ORA, IndirectY1 },
  { SBC, IndirectY1 },
  { STA, IndirectY1 },

  { ADC, IndirectY2 },
  { AND, IndirectY2 },
  { CMP, IndirectY2 },
  { EOR, IndirectY2 },
  { LDA, IndirectY2 },
  { ORA, IndirectY2 },
  { SBC, IndirectY2 },
  { STA, IndirectY2 },

  { ADC, IndirectY3 },
  { AND, IndirectY3 },
  { CMP, IndirectY3 },
  { EOR, IndirectY3 },
  { LDA, IndirectY3 },
  { ORA, IndirectY3 },
  { SBC, IndirectY3 },
  { STA, IndirectY3 },

  { JMP, Indirect0 },
  { JMP, Indirect1 },
  { JMP, Indirect2 },

  { BPL, Absolute0 },
  { BMI, Absolute0 },
  { BVC, Absolute0 },
  { BVS, Absolute0 },
  { BCC, Absolute0 },
  { BCS, Absolute0 },
  { BNE, Absolute0 },
  { BEQ, Absolute0 },

  { BPL, Absolute1 },
  { BMI, Absolute1 },
  { BVC, Absolute1 },
  { BVS, Absolute1 },
  { BCC, Absolute1 },
  { BCS, Absolute1 },
  { BNE, Absolute1 },
  { BEQ, Absolute1 },

  { BPL, Absolute2 },
  { BMI, Absolute2 },
  { BVC, Absolute2 },
  { BVS, Absolute2 },
  { BCC, Absolute2 },
  { BCS, Absolute2 },
  { BNE, Absolute2 },
  { BEQ, Absolute2 },

  { ASL_A, None },
  { CLC, None },
  { SEC, None },
  { CLI, None },
  { SEI, None },
  { CLV, None },
  { CLD, None },
  { SED, None },
  { LSR_A, None },
  // { NOP, None },
  { TAX, None },
  { TXA, None },
  { DEX, None },
  { INX, None },
  { TAY, None },
  { TYA, None },
  { DEY, None },
  { INY, None },
  { ROL_A, None },
  { ROR_A, None },
  { RTI, None },
  { RTS, None },
  { TXS, None },
  { TSX, None },
  { PHA, None },
  { PLA, None },
  { PHP, None },
  { PLP, None },
};
