
#pragma once

#include "operations.h"

struct opcode {
  Operations op;
  AddrMode mode;

  bool operator==(const opcode& other) const {
    return op == other.op && mode == other.mode;
  }

  bool operator!=(const opcode& other) const {
    return !(*this == other);
  }

  bool operator <(const opcode& other) const {
    return op < other.op ? true : op > other.op ? false : mode < other.mode;
  }

  const static opcode zero;
};

const opcode opcode::zero = opcode { (Operations)0, (AddrMode)0 };


opcode opcodes[] = {
  { ADC, Immediate0 },
  // { AND, Immediate0 }, // same as LDA #0
  { CMP, Immediate0 },
  { CPX, Immediate0 },
  { CPY, Immediate0 },
  // { EOR, Immediate0 }, // same as ORA #0
  { LDA, Immediate0 },
  { LDX, Immediate0 },
  { LDY, Immediate0 },
  { ORA, Immediate0 },
  { SBC, Immediate0 },

  { ADC, Immediate1 },
  { AND, Immediate1 },
  { CMP, Immediate1 },
  { CPX, Immediate1 },
  { CPY, Immediate1 },
  { EOR, Immediate1 },
  { LDA, Immediate1 },
  { LDX, Immediate1 },
  { LDY, Immediate1 },
  { ORA, Immediate1 },
  { SBC, Immediate1 },

  { ADC, ImmediateC0 },
  { AND, ImmediateC0 },
  { CMP, ImmediateC0 },
  { CPX, ImmediateC0 },
  { CPY, ImmediateC0 },
  { EOR, ImmediateC0 },
  { LDA, ImmediateC0 },
  { LDX, ImmediateC0 },
  { LDY, ImmediateC0 },
  { ORA, ImmediateC0 },
  { SBC, ImmediateC0 },

  { ADC, ImmediateC1 },
  { AND, ImmediateC1 },
  { CMP, ImmediateC1 },
  { CPX, ImmediateC1 },
  { CPY, ImmediateC1 },
  { EOR, ImmediateC1 },
  { LDA, ImmediateC1 },
  { LDX, ImmediateC1 },
  { LDY, ImmediateC1 },
  { ORA, ImmediateC1 },
  { SBC, ImmediateC1 },

  { ADC, ImmediateC0Plus1 },
  { AND, ImmediateC0Plus1 },
  { CMP, ImmediateC0Plus1 },
  { CPX, ImmediateC0Plus1 },
  { CPY, ImmediateC0Plus1 },
  { EOR, ImmediateC0Plus1 },
  { LDA, ImmediateC0Plus1 },
  { LDX, ImmediateC0Plus1 },
  { LDY, ImmediateC0Plus1 },
  { ORA, ImmediateC0Plus1 },
  { SBC, ImmediateC0Plus1 },

  { ADC, ImmediateC1Plus1 },
  { AND, ImmediateC1Plus1 },
  { CMP, ImmediateC1Plus1 },
  { CPX, ImmediateC1Plus1 },
  { CPY, ImmediateC1Plus1 },
  { EOR, ImmediateC1Plus1 },
  { LDA, ImmediateC1Plus1 },
  { LDX, ImmediateC1Plus1 },
  { LDY, ImmediateC1Plus1 },
  { ORA, ImmediateC1Plus1 },
  { SBC, ImmediateC1Plus1 },

  { ADC, ImmediateC0PlusC1 },
  { AND, ImmediateC0PlusC1 },
  { CMP, ImmediateC0PlusC1 },
  { CPX, ImmediateC0PlusC1 },
  { CPY, ImmediateC0PlusC1 },
  { EOR, ImmediateC0PlusC1 },
  { LDA, ImmediateC0PlusC1 },
  { LDX, ImmediateC0PlusC1 },
  { LDY, ImmediateC0PlusC1 },
  { ORA, ImmediateC0PlusC1 },
  { SBC, ImmediateC0PlusC1 },

  { ADC, ZeroPage0 },
  { AND, ZeroPage0 },
  { ASL, ZeroPage0 },
  { BIT, ZeroPage0 },
  { CMP, ZeroPage0 },
  { CPX, ZeroPage0 },
  { CPY, ZeroPage0 },
  { DEC, ZeroPage0 },
  { EOR, ZeroPage0 },
  { INC, ZeroPage0 },
  { LDA, ZeroPage0 },
  { LDX, ZeroPage0 },
  { LDY, ZeroPage0 },
  { LSR, ZeroPage0 },
  { ORA, ZeroPage0 },
  { ROL, ZeroPage0 },
  { ROR, ZeroPage0 },
  { SBC, ZeroPage0 },
  { STA, ZeroPage0 },
  { STX, ZeroPage0 },
  { STY, ZeroPage0 },

  { ADC, ZeroPage1 },
  { AND, ZeroPage1 },
  { ASL, ZeroPage1 },
  { BIT, ZeroPage1 },
  { CMP, ZeroPage1 },
  { CPX, ZeroPage1 },
  { CPY, ZeroPage1 },
  { DEC, ZeroPage1 },
  { EOR, ZeroPage1 },
  { INC, ZeroPage1 },
  { LDA, ZeroPage1 },
  { LDX, ZeroPage1 },
  { LDY, ZeroPage1 },
  { LSR, ZeroPage1 },
  { ORA, ZeroPage1 },
  { ROL, ZeroPage1 },
  { ROR, ZeroPage1 },
  { SBC, ZeroPage1 },
  { STA, ZeroPage1 },
  { STX, ZeroPage1 },
  { STY, ZeroPage1 },

  { ADC, ZeroPage2 },
  { AND, ZeroPage2 },
  { ASL, ZeroPage2 },
  { BIT, ZeroPage2 },
  { CMP, ZeroPage2 },
  { CPX, ZeroPage2 },
  { CPY, ZeroPage2 },
  { DEC, ZeroPage2 },
  { EOR, ZeroPage2 },
  { INC, ZeroPage2 },
  { LDA, ZeroPage2 },
  { LDX, ZeroPage2 },
  { LDY, ZeroPage2 },
  { LSR, ZeroPage2 },
  { ORA, ZeroPage2 },
  { ROL, ZeroPage2 },
  { ROR, ZeroPage2 },
  { SBC, ZeroPage2 },
  { STA, ZeroPage2 },
  { STX, ZeroPage2 },
  { STY, ZeroPage2 },

  { ADC, ZeroPage3 },
  { AND, ZeroPage3 },
  { ASL, ZeroPage3 },
  { BIT, ZeroPage3 },
  { CMP, ZeroPage3 },
  { CPX, ZeroPage3 },
  { CPY, ZeroPage3 },
  { DEC, ZeroPage3 },
  { EOR, ZeroPage3 },
  { INC, ZeroPage3 },
  { LDA, ZeroPage3 },
  { LDX, ZeroPage3 },
  { LDY, ZeroPage3 },
  { LSR, ZeroPage3 },
  { ORA, ZeroPage3 },
  { ROL, ZeroPage3 },
  { ROR, ZeroPage3 },
  { SBC, ZeroPage3 },
  { STA, ZeroPage3 },
  { STX, ZeroPage3 },
  { STY, ZeroPage3 },

  { ADC, ZeroPageX0 },
  { AND, ZeroPageX0 },
  { ASL, ZeroPageX0 },
  { CMP, ZeroPageX0 },
  { DEC, ZeroPageX0 },
  { EOR, ZeroPageX0 },
  { INC, ZeroPageX0 },
  { LDA, ZeroPageX0 },
  { LDY, ZeroPageX0 },
  { LSR, ZeroPageX0 },
  { ORA, ZeroPageX0 },
  { ROL, ZeroPageX0 },
  { ROR, ZeroPageX0 },
  { SBC, ZeroPageX0 },
  { STA, ZeroPageX0 },
  { STY, ZeroPageX0 },

  { ADC, ZeroPageX1 },
  { AND, ZeroPageX1 },
  { ASL, ZeroPageX1 },
  { CMP, ZeroPageX1 },
  { DEC, ZeroPageX1 },
  { EOR, ZeroPageX1 },
  { INC, ZeroPageX1 },
  { LDA, ZeroPageX1 },
  { LDY, ZeroPageX1 },
  { LSR, ZeroPageX1 },
  { ORA, ZeroPageX1 },
  { ROL, ZeroPageX1 },
  { ROR, ZeroPageX1 },
  { SBC, ZeroPageX1 },
  { STA, ZeroPageX1 },
  { STY, ZeroPageX1 },

  { ADC, ZeroPageX2 },
  { AND, ZeroPageX2 },
  { ASL, ZeroPageX2 },
  { CMP, ZeroPageX2 },
  { DEC, ZeroPageX2 },
  { EOR, ZeroPageX2 },
  { INC, ZeroPageX2 },
  { LDA, ZeroPageX2 },
  { LDY, ZeroPageX2 },
  { LSR, ZeroPageX2 },
  { ORA, ZeroPageX2 },
  { ROL, ZeroPageX2 },
  { ROR, ZeroPageX2 },
  { SBC, ZeroPageX2 },
  { STA, ZeroPageX2 },
  { STY, ZeroPageX2 },

  { ADC, ZeroPageX3 },
  { AND, ZeroPageX3 },
  { ASL, ZeroPageX3 },
  { CMP, ZeroPageX3 },
  { DEC, ZeroPageX3 },
  { EOR, ZeroPageX3 },
  { INC, ZeroPageX3 },
  { LDA, ZeroPageX3 },
  { LDY, ZeroPageX3 },
  { LSR, ZeroPageX3 },
  { ORA, ZeroPageX3 },
  { ROL, ZeroPageX3 },
  { ROR, ZeroPageX3 },
  { SBC, ZeroPageX3 },
  { STA, ZeroPageX3 },
  { STY, ZeroPageX3 },

  { LDX, ZeroPageY0 },
  { STX, ZeroPageY0 },
  { LDX, ZeroPageY1 },
  { STX, ZeroPageY1 },
  { LDX, ZeroPageY2 },
  { STX, ZeroPageY2 },
  { LDX, ZeroPageY3 },
  { STX, ZeroPageY3 },

  { ADC, Absolute0 },
  { AND, Absolute0 },
  { ASL, Absolute0 },
  { BIT, Absolute0 },
  { CMP, Absolute0 },
  { CPX, Absolute0 },
  { CPY, Absolute0 },
  { DEC, Absolute0 },
  { EOR, Absolute0 },
  { INC, Absolute0 },
  { JMP, Absolute0 },
  { LDA, Absolute0 },
  { LDX, Absolute0 },
  { LDY, Absolute0 },
  { LSR, Absolute0 },
  { ORA, Absolute0 },
  { ROL, Absolute0 },
  { ROR, Absolute0 },
  { SBC, Absolute0 },
  { STA, Absolute0 },
  { STX, Absolute0 },
  { STY, Absolute0 },

  { ADC, Absolute1 },
  { AND, Absolute1 },
  { ASL, Absolute1 },
  { BIT, Absolute1 },
  { CMP, Absolute1 },
  { CPX, Absolute1 },
  { CPY, Absolute1 },
  { DEC, Absolute1 },
  { EOR, Absolute1 },
  { INC, Absolute1 },
  { JMP, Absolute1 },
  { LDA, Absolute1 },
  { LDX, Absolute1 },
  { LDY, Absolute1 },
  { LSR, Absolute1 },
  { ORA, Absolute1 },
  { ROL, Absolute1 },
  { ROR, Absolute1 },
  { SBC, Absolute1 },
  { STA, Absolute1 },
  { STX, Absolute1 },
  { STY, Absolute1 },

  { ADC, Absolute2 },
  { AND, Absolute2 },
  { ASL, Absolute2 },
  { BIT, Absolute2 },
  { CMP, Absolute2 },
  { CPX, Absolute2 },
  { CPY, Absolute2 },
  { DEC, Absolute2 },
  { EOR, Absolute2 },
  { INC, Absolute2 },
  { JMP, Absolute2 },
  { LDA, Absolute2 },
  { LDX, Absolute2 },
  { LDY, Absolute2 },
  { LSR, Absolute2 },
  { ORA, Absolute2 },
  { ROL, Absolute2 },
  { ROR, Absolute2 },
  { SBC, Absolute2 },
  { STA, Absolute2 },
  { STX, Absolute2 },
  { STY, Absolute2 },

  { ADC, AbsoluteX0 },
  { AND, AbsoluteX0 },
  { ASL, AbsoluteX0 },
  { CMP, AbsoluteX0 },
  { DEC, AbsoluteX0 },
  { EOR, AbsoluteX0 },
  { INC, AbsoluteX0 },
  { LDA, AbsoluteX0 },
  { LDY, AbsoluteX0 },
  { LSR, AbsoluteX0 },
  { ORA, AbsoluteX0 },
  { ROL, AbsoluteX0 },
  { ROR, AbsoluteX0 },
  { SBC, AbsoluteX0 },
  { STA, AbsoluteX0 },

  { ADC, AbsoluteX1 },
  { AND, AbsoluteX1 },
  { ASL, AbsoluteX1 },
  { CMP, AbsoluteX1 },
  { DEC, AbsoluteX1 },
  { EOR, AbsoluteX1 },
  { INC, AbsoluteX1 },
  { LDA, AbsoluteX1 },
  { LDY, AbsoluteX1 },
  { LSR, AbsoluteX1 },
  { ORA, AbsoluteX1 },
  { ROL, AbsoluteX1 },
  { ROR, AbsoluteX1 },
  { SBC, AbsoluteX1 },
  { STA, AbsoluteX1 },

  { ADC, AbsoluteX2 },
  { AND, AbsoluteX2 },
  { ASL, AbsoluteX2 },
  { CMP, AbsoluteX2 },
  { DEC, AbsoluteX2 },
  { EOR, AbsoluteX2 },
  { INC, AbsoluteX2 },
  { LDA, AbsoluteX2 },
  { LDY, AbsoluteX2 },
  { LSR, AbsoluteX2 },
  { ORA, AbsoluteX2 },
  { ROL, AbsoluteX2 },
  { ROR, AbsoluteX2 },
  { SBC, AbsoluteX2 },
  { STA, AbsoluteX2 },

  { ADC, AbsoluteY0 },
  { AND, AbsoluteY0 },
  { EOR, AbsoluteY0 },
  { LDA, AbsoluteY0 },
  { LDX, AbsoluteY0 },
  { ORA, AbsoluteY0 },
  { SBC, AbsoluteY0 },
  { STA, AbsoluteY0 },

  { ADC, AbsoluteY1 },
  { AND, AbsoluteY1 },
  { EOR, AbsoluteY1 },
  { LDA, AbsoluteY1 },
  { LDX, AbsoluteY1 },
  { ORA, AbsoluteY1 },
  { SBC, AbsoluteY1 },
  { STA, AbsoluteY1 },

  { ADC, AbsoluteY2 },
  { AND, AbsoluteY2 },
  { EOR, AbsoluteY2 },
  { LDA, AbsoluteY2 },
  { LDX, AbsoluteY2 },
  { ORA, AbsoluteY2 },
  { SBC, AbsoluteY2 },
  { STA, AbsoluteY2 },

  { ADC, IndirectX0 },
  { AND, IndirectX0 },
  { CMP, IndirectX0 },
  { EOR, IndirectX0 },
  { LDA, IndirectX0 },
  { ORA, IndirectX0 },
  { SBC, IndirectX0 },
  { STA, IndirectX0 },

  { ADC, IndirectX1 },
  { AND, IndirectX1 },
  { CMP, IndirectX1 },
  { EOR, IndirectX1 },
  { LDA, IndirectX1 },
  { ORA, IndirectX1 },
  { SBC, IndirectX1 },
  { STA, IndirectX1 },

  { ADC, IndirectX2 },
  { AND, IndirectX2 },
  { CMP, IndirectX2 },
  { EOR, IndirectX2 },
  { LDA, IndirectX2 },
  { ORA, IndirectX2 },
  { SBC, IndirectX2 },
  { STA, IndirectX2 },

  { ADC, IndirectX3 },
  { AND, IndirectX3 },
  { CMP, IndirectX3 },
  { EOR, IndirectX3 },
  { LDA, IndirectX3 },
  { ORA, IndirectX3 },
  { SBC, IndirectX3 },
  { STA, IndirectX3 },

  { ADC, IndirectY0 },
  { AND, IndirectY0 },
  { CMP, IndirectY0 },
  { EOR, IndirectY0 },
  { LDA, IndirectY0 },
  { ORA, IndirectY0 },
  { SBC, IndirectY0 },
  { STA, IndirectY0 },

  { ADC, IndirectY1 },
  { AND, IndirectY1 },
  { CMP, IndirectY1 },
  { EOR, IndirectY1 },
  { LDA, IndirectY1 },
  { ORA, IndirectY1 },
  { SBC, IndirectY1 },
  { STA, IndirectY1 },

  { ADC, IndirectY2 },
  { AND, IndirectY2 },
  { CMP, IndirectY2 },
  { EOR, IndirectY2 },
  { LDA, IndirectY2 },
  { ORA, IndirectY2 },
  { SBC, IndirectY2 },
  { STA, IndirectY2 },

  { ADC, IndirectY3 },
  { AND, IndirectY3 },
  { CMP, IndirectY3 },
  { EOR, IndirectY3 },
  { LDA, IndirectY3 },
  { ORA, IndirectY3 },
  { SBC, IndirectY3 },
  { STA, IndirectY3 },

  { JMP, Indirect0 },
  { JMP, Indirect1 },
  { JMP, Indirect2 },

  { BPL, Absolute0 },
  { BMI, Absolute0 },
  { BVC, Absolute0 },
  { BVS, Absolute0 },
  { BCC, Absolute0 },
  { BCS, Absolute0 },
  { BNE, Absolute0 },
  { BEQ, Absolute0 },

  { BPL, Absolute1 },
  { BMI, Absolute1 },
  { BVC, Absolute1 },
  { BVS, Absolute1 },
  { BCC, Absolute1 },
  { BCS, Absolute1 },
  { BNE, Absolute1 },
  { BEQ, Absolute1 },

  { BPL, Absolute2 },
  { BMI, Absolute2 },
  { BVC, Absolute2 },
  { BVS, Absolute2 },
  { BCC, Absolute2 },
  { BCS, Absolute2 },
  { BNE, Absolute2 },
  { BEQ, Absolute2 },

  { ASL_A, None },
  { CLC, None },
  { SEC, None },
  { CLI, None },
  { SEI, None },
  { CLV, None },
  { CLD, None },
  { SED, None },
  { LSR_A, None },
  // { NOP, None },
  { TAX, None },
  { TXA, None },
  { DEX, None },
  { INX, None },
  { TAY, None },
  { TYA, None },
  { DEY, None },
  { INY, None },
  { ROL_A, None },
  { ROR_A, None },
  { RTI, None },
  { RTS, None },
  { TXS, None },
  { TSX, None },
  { PHA, None },
  { PLA, None },
  { PHP, None },
  { PLP, None },
};

std::map<opcode, float> operation_costs {
  { { (Operations)0, (AddrMode)0 }, 0 },
  { {ADC, Immediate0 }, 2 },
  { {ADC, Immediate0 }, 2 },
  { { ADC, Immediate0 }, 2 },
  { { AND, Immediate0 }, 2 },
  { { CMP, Immediate0 }, 2 },
  { { CPX, Immediate0 }, 2 },
  { { CPY, Immediate0 }, 2 },
  { { EOR, Immediate0 }, 2 },
  { { LDA, Immediate0 }, 2 },
  { { LDX, Immediate0 }, 2 },
  { { LDY, Immediate0 }, 2 },
  { { ORA, Immediate0 }, 2 },
  { { SBC, Immediate0 }, 2 },

  { { ADC, Immediate1 }, 2 },
  { { AND, Immediate1 }, 2 },
  { { CMP, Immediate1 }, 2 },
  { { CPX, Immediate1 }, 2 },
  { { CPY, Immediate1 }, 2 },
  { { EOR, Immediate1 }, 2 },
  { { LDA, Immediate1 }, 2 },
  { { LDX, Immediate1 }, 2 },
  { { LDY, Immediate1 }, 2 },
  { { ORA, Immediate1 }, 2 },
  { { SBC, Immediate1 }, 2 },

  { { ADC, ImmediateC0 }, 2 },
  { { AND, ImmediateC0 }, 2 },
  { { CMP, ImmediateC0 }, 2 },
  { { CPX, ImmediateC0 }, 2 },
  { { CPY, ImmediateC0 }, 2 },
  { { EOR, ImmediateC0 }, 2 },
  { { LDA, ImmediateC0 }, 2 },
  { { LDX, ImmediateC0 }, 2 },
  { { LDY, ImmediateC0 }, 2 },
  { { ORA, ImmediateC0 }, 2 },
  { { SBC, ImmediateC0 }, 2 },

  { { ADC, ImmediateC1 }, 2 },
  { { AND, ImmediateC1 }, 2 },
  { { CMP, ImmediateC1 }, 2 },
  { { CPX, ImmediateC1 }, 2 },
  { { CPY, ImmediateC1 }, 2 },
  { { EOR, ImmediateC1 }, 2 },
  { { LDA, ImmediateC1 }, 2 },
  { { LDX, ImmediateC1 }, 2 },
  { { LDY, ImmediateC1 }, 2 },
  { { ORA, ImmediateC1 }, 2 },
  { { SBC, ImmediateC1 }, 2 },

  { { ADC, ImmediateC0Plus1 }, 2 },
  { { AND, ImmediateC0Plus1 }, 2 },
  { { CMP, ImmediateC0Plus1 }, 2 },
  { { CPX, ImmediateC0Plus1 }, 2 },
  { { CPY, ImmediateC0Plus1 }, 2 },
  { { EOR, ImmediateC0Plus1 }, 2 },
  { { LDA, ImmediateC0Plus1 }, 2 },
  { { LDX, ImmediateC0Plus1 }, 2 },
  { { LDY, ImmediateC0Plus1 }, 2 },
  { { ORA, ImmediateC0Plus1 }, 2 },
  { { SBC, ImmediateC0Plus1 }, 2 },

  { { ADC, ImmediateC1Plus1 }, 2 },
  { { AND, ImmediateC1Plus1 }, 2 },
  { { CMP, ImmediateC1Plus1 }, 2 },
  { { CPX, ImmediateC1Plus1 }, 2 },
  { { CPY, ImmediateC1Plus1 }, 2 },
  { { EOR, ImmediateC1Plus1 }, 2 },
  { { LDA, ImmediateC1Plus1 }, 2 },
  { { LDX, ImmediateC1Plus1 }, 2 },
  { { LDY, ImmediateC1Plus1 }, 2 },
  { { ORA, ImmediateC1Plus1 }, 2 },
  { { SBC, ImmediateC1Plus1 }, 2 },

  { { ADC, ImmediateC0PlusC1 }, 2 },
  { { AND, ImmediateC0PlusC1 }, 2 },
  { { CMP, ImmediateC0PlusC1 }, 2 },
  { { CPX, ImmediateC0PlusC1 }, 2 },
  { { CPY, ImmediateC0PlusC1 }, 2 },
  { { EOR, ImmediateC0PlusC1 }, 2 },
  { { LDA, ImmediateC0PlusC1 }, 2 },
  { { LDX, ImmediateC0PlusC1 }, 2 },
  { { LDY, ImmediateC0PlusC1 }, 2 },
  { { ORA, ImmediateC0PlusC1 }, 2 },
  { { SBC, ImmediateC0PlusC1 }, 2 },

  { { ADC, ZeroPage0 }, 3 },
  { { AND, ZeroPage0 }, 3 },
  { { BIT, ZeroPage0 }, 3 },
  { { CMP, ZeroPage0 }, 3 },
  { { CPX, ZeroPage0 }, 3 },
  { { CPY, ZeroPage0 }, 3 },
  { { EOR, ZeroPage0 }, 3 },
  { { LDA, ZeroPage0 }, 3 },
  { { LDX, ZeroPage0 }, 3 },
  { { LDY, ZeroPage0 }, 3 },
  { { ORA, ZeroPage0 }, 3 },
  { { SBC, ZeroPage0 }, 3 },
  { { STA, ZeroPage0 }, 3 },
  { { STX, ZeroPage0 }, 3 },
  { { STY, ZeroPage0 }, 3 },
  { { DEC, ZeroPage0 }, 5 },
  { { INC, ZeroPage0 }, 5 },
  { { ASL, ZeroPage0 }, 5 },
  { { LSR, ZeroPage0 }, 5 },
  { { ROL, ZeroPage0 }, 5 },
  { { ROR, ZeroPage0 }, 5 },

  { { ADC, ZeroPage1 }, 3 },
  { { AND, ZeroPage1 }, 3 },
  { { BIT, ZeroPage1 }, 3 },
  { { CMP, ZeroPage1 }, 3 },
  { { CPX, ZeroPage1 }, 3 },
  { { CPY, ZeroPage1 }, 3 },
  { { EOR, ZeroPage1 }, 3 },
  { { LDA, ZeroPage1 }, 3 },
  { { LDX, ZeroPage1 }, 3 },
  { { LDY, ZeroPage1 }, 3 },
  { { ORA, ZeroPage1 }, 3 },
  { { SBC, ZeroPage1 }, 3 },
  { { STA, ZeroPage1 }, 3 },
  { { STX, ZeroPage1 }, 3 },
  { { STY, ZeroPage1 }, 3 },
  { { DEC, ZeroPage1 }, 5 },
  { { INC, ZeroPage1 }, 5 },
  { { ASL, ZeroPage1 }, 5 },
  { { LSR, ZeroPage1 }, 5 },
  { { ROL, ZeroPage1 }, 5 },
  { { ROR, ZeroPage1 }, 5 },

  { { ADC, ZeroPage1 }, 3 },
  { { AND, ZeroPage1 }, 3 },
  { { BIT, ZeroPage1 }, 3 },
  { { CMP, ZeroPage1 }, 3 },
  { { CPX, ZeroPage1 }, 3 },
  { { CPY, ZeroPage1 }, 3 },
  { { EOR, ZeroPage1 }, 3 },
  { { LDA, ZeroPage1 }, 3 },
  { { LDX, ZeroPage1 }, 3 },
  { { LDY, ZeroPage1 }, 3 },
  { { ORA, ZeroPage1 }, 3 },
  { { SBC, ZeroPage1 }, 3 },
  { { STA, ZeroPage1 }, 3 },
  { { STX, ZeroPage1 }, 3 },
  { { STY, ZeroPage1 }, 3 },
  { { DEC, ZeroPage1 }, 5 },
  { { INC, ZeroPage1 }, 5 },
  { { ASL, ZeroPage1 }, 5 },
  { { LSR, ZeroPage1 }, 5 },
  { { ROL, ZeroPage1 }, 5 },
  { { ROR, ZeroPage1 }, 5 },

  { { ADC, ZeroPage2 }, 3 },
  { { AND, ZeroPage2 }, 3 },
  { { BIT, ZeroPage2 }, 3 },
  { { CMP, ZeroPage2 }, 3 },
  { { CPX, ZeroPage2 }, 3 },
  { { CPY, ZeroPage2 }, 3 },
  { { EOR, ZeroPage2 }, 3 },
  { { LDA, ZeroPage2 }, 3 },
  { { LDX, ZeroPage2 }, 3 },
  { { LDY, ZeroPage2 }, 3 },
  { { ORA, ZeroPage2 }, 3 },
  { { SBC, ZeroPage2 }, 3 },
  { { STA, ZeroPage2 }, 3 },
  { { STX, ZeroPage2 }, 3 },
  { { STY, ZeroPage2 }, 3 },
  { { DEC, ZeroPage2 }, 5 },
  { { INC, ZeroPage2 }, 5 },
  { { ASL, ZeroPage2 }, 5 },
  { { LSR, ZeroPage2 }, 5 },
  { { ROL, ZeroPage2 }, 5 },
  { { ROR, ZeroPage2 }, 5 },

  { { ADC, ZeroPage3 }, 3 },
  { { AND, ZeroPage3 }, 3 },
  { { BIT, ZeroPage3 }, 3 },
  { { CMP, ZeroPage3 }, 3 },
  { { CPX, ZeroPage3 }, 3 },
  { { CPY, ZeroPage3 }, 3 },
  { { EOR, ZeroPage3 }, 3 },
  { { LDA, ZeroPage3 }, 3 },
  { { LDX, ZeroPage3 }, 3 },
  { { LDY, ZeroPage3 }, 3 },
  { { ORA, ZeroPage3 }, 3 },
  { { SBC, ZeroPage3 }, 3 },
  { { STA, ZeroPage3 }, 3 },
  { { STX, ZeroPage3 }, 3 },
  { { STY, ZeroPage3 }, 3 },
  { { DEC, ZeroPage3 }, 5 },
  { { INC, ZeroPage3 }, 5 },
  { { ASL, ZeroPage3 }, 5 },
  { { LSR, ZeroPage3 }, 5 },
  { { ROL, ZeroPage3 }, 5 },
  { { ROR, ZeroPage3 }, 5 },

  { { ADC, ZeroPageX0 }, 4 },
  { { AND, ZeroPageX0 }, 4 },
  { { CMP, ZeroPageX0 }, 4 },
  { { EOR, ZeroPageX0 }, 4 },
  { { LDA, ZeroPageX0 }, 4 },
  { { LDY, ZeroPageX0 }, 4 },
  { { ORA, ZeroPageX0 }, 4 },
  { { SBC, ZeroPageX0 }, 4 },
  { { STA, ZeroPageX0 }, 4 },
  { { STY, ZeroPageX0 }, 4 },
  { { ASL, ZeroPageX0 }, 6 },
  { { DEC, ZeroPageX0 }, 6 },
  { { INC, ZeroPageX0 }, 6 },
  { { LSR, ZeroPageX0 }, 6 },
  { { ROL, ZeroPageX0 }, 6 },
  { { ROR, ZeroPageX0 }, 6 },

  { { ADC, ZeroPageX1 }, 4 },
  { { AND, ZeroPageX1 }, 4 },
  { { CMP, ZeroPageX1 }, 4 },
  { { EOR, ZeroPageX1 }, 4 },
  { { LDA, ZeroPageX1 }, 4 },
  { { LDY, ZeroPageX1 }, 4 },
  { { ORA, ZeroPageX1 }, 4 },
  { { SBC, ZeroPageX1 }, 4 },
  { { STA, ZeroPageX1 }, 4 },
  { { STY, ZeroPageX1 }, 4 },
  { { ASL, ZeroPageX1 }, 6 },
  { { DEC, ZeroPageX1 }, 6 },
  { { INC, ZeroPageX1 }, 6 },
  { { LSR, ZeroPageX1 }, 6 },
  { { ROL, ZeroPageX1 }, 6 },
  { { ROR, ZeroPageX1 }, 6 },

  { { ADC, ZeroPageX2 }, 4 },
  { { AND, ZeroPageX2 }, 4 },
  { { CMP, ZeroPageX2 }, 4 },
  { { EOR, ZeroPageX2 }, 4 },
  { { LDA, ZeroPageX2 }, 4 },
  { { LDY, ZeroPageX2 }, 4 },
  { { ORA, ZeroPageX2 }, 4 },
  { { SBC, ZeroPageX2 }, 4 },
  { { STA, ZeroPageX2 }, 4 },
  { { STY, ZeroPageX2 }, 4 },
  { { ASL, ZeroPageX2 }, 6 },
  { { DEC, ZeroPageX2 }, 6 },
  { { INC, ZeroPageX2 }, 6 },
  { { LSR, ZeroPageX2 }, 6 },
  { { ROL, ZeroPageX2 }, 6 },
  { { ROR, ZeroPageX2 }, 6 },

  { { ADC, ZeroPageX3 }, 4 },
  { { AND, ZeroPageX3 }, 4 },
  { { CMP, ZeroPageX3 }, 4 },
  { { EOR, ZeroPageX3 }, 4 },
  { { LDA, ZeroPageX3 }, 4 },
  { { LDY, ZeroPageX3 }, 4 },
  { { ORA, ZeroPageX3 }, 4 },
  { { SBC, ZeroPageX3 }, 4 },
  { { STA, ZeroPageX3 }, 4 },
  { { STY, ZeroPageX3 }, 4 },
  { { ASL, ZeroPageX3 }, 6 },
  { { DEC, ZeroPageX3 }, 6 },
  { { INC, ZeroPageX3 }, 6 },
  { { LSR, ZeroPageX3 }, 6 },
  { { ROL, ZeroPageX3 }, 6 },
  { { ROR, ZeroPageX3 }, 6 },

  { { LDX, ZeroPageY0 }, 4 },
  { { STX, ZeroPageY0 }, 4 },
  { { LDX, ZeroPageY1 }, 4 },
  { { STX, ZeroPageY1 }, 4 },
  { { LDX, ZeroPageY2 }, 4 },
  { { STX, ZeroPageY2 }, 4 },
  { { LDX, ZeroPageY3 }, 4 },
  { { STX, ZeroPageY3 }, 4 },

  { { JMP, Absolute0 }, 3 },
  { { ADC, Absolute0 }, 4 },
  { { AND, Absolute0 }, 4 },
  { { BIT, Absolute0 }, 4 },
  { { CMP, Absolute0 }, 4 },
  { { CPX, Absolute0 }, 4 },
  { { CPY, Absolute0 }, 4 },
  { { EOR, Absolute0 }, 4 },
  { { LDA, Absolute0 }, 4 },
  { { LDX, Absolute0 }, 4 },
  { { LDY, Absolute0 }, 4 },
  { { ORA, Absolute0 }, 4 },
  { { SBC, Absolute0 }, 4 },
  { { STA, Absolute0 }, 4 },
  { { STX, Absolute0 }, 4 },
  { { STY, Absolute0 }, 4 },
  { { ASL, Absolute0 }, 6 },
  { { DEC, Absolute0 }, 6 },
  { { INC, Absolute0 }, 6 },
  { { LSR, Absolute0 }, 6 },
  { { ROL, Absolute0 }, 6 },
  { { ROR, Absolute0 }, 6 },

  { { JMP, Absolute1 }, 3 },
  { { ADC, Absolute1 }, 4 },
  { { AND, Absolute1 }, 4 },
  { { BIT, Absolute1 }, 4 },
  { { CMP, Absolute1 }, 4 },
  { { CPX, Absolute1 }, 4 },
  { { CPY, Absolute1 }, 4 },
  { { EOR, Absolute1 }, 4 },
  { { LDA, Absolute1 }, 4 },
  { { LDX, Absolute1 }, 4 },
  { { LDY, Absolute1 }, 4 },
  { { ORA, Absolute1 }, 4 },
  { { SBC, Absolute1 }, 4 },
  { { STA, Absolute1 }, 4 },
  { { STX, Absolute1 }, 4 },
  { { STY, Absolute1 }, 4 },
  { { ASL, Absolute1 }, 6 },
  { { DEC, Absolute1 }, 6 },
  { { INC, Absolute1 }, 6 },
  { { LSR, Absolute1 }, 6 },
  { { ROL, Absolute1 }, 6 },
  { { ROR, Absolute1 }, 6 },

  { { JMP, Absolute2 }, 3 },
  { { ADC, Absolute2 }, 4 },
  { { AND, Absolute2 }, 4 },
  { { BIT, Absolute2 }, 4 },
  { { CMP, Absolute2 }, 4 },
  { { CPX, Absolute2 }, 4 },
  { { CPY, Absolute2 }, 4 },
  { { EOR, Absolute2 }, 4 },
  { { LDA, Absolute2 }, 4 },
  { { LDX, Absolute2 }, 4 },
  { { LDY, Absolute2 }, 4 },
  { { ORA, Absolute2 }, 4 },
  { { SBC, Absolute2 }, 4 },
  { { STA, Absolute2 }, 4 },
  { { STX, Absolute2 }, 4 },
  { { STY, Absolute2 }, 4 },
  { { ASL, Absolute2 }, 6 },
  { { DEC, Absolute2 }, 6 },
  { { INC, Absolute2 }, 6 },
  { { LSR, Absolute2 }, 6 },
  { { ROL, Absolute2 }, 6 },
  { { ROR, Absolute2 }, 6 },

  { { ADC, AbsoluteX0 }, 4.1 },
  { { AND, AbsoluteX0 }, 4.1 },
  { { CMP, AbsoluteX0 }, 4.1 },
  { { EOR, AbsoluteX0 }, 4.1 },
  { { LDA, AbsoluteX0 }, 4.1 },
  { { LDY, AbsoluteX0 }, 4.1 },
  { { ORA, AbsoluteX0 }, 4.1 },
  { { SBC, AbsoluteX0 }, 4.1 },
  { { STA, AbsoluteX0 }, 4.1 },
  { { ASL, AbsoluteX0 }, 6 },
  { { DEC, AbsoluteX0 }, 6 },
  { { INC, AbsoluteX0 }, 6 },
  { { LSR, AbsoluteX0 }, 6 },
  { { ROL, AbsoluteX0 }, 6 },
  { { ROR, AbsoluteX0 }, 6 },

  { { ADC, AbsoluteX1 }, 4.1 },
  { { AND, AbsoluteX1 }, 4.1 },
  { { CMP, AbsoluteX1 }, 4.1 },
  { { EOR, AbsoluteX1 }, 4.1 },
  { { LDA, AbsoluteX1 }, 4.1 },
  { { LDY, AbsoluteX1 }, 4.1 },
  { { ORA, AbsoluteX1 }, 4.1 },
  { { SBC, AbsoluteX1 }, 4.1 },
  { { STA, AbsoluteX1 }, 4.1 },
  { { ASL, AbsoluteX1 }, 6 },
  { { DEC, AbsoluteX1 }, 6 },
  { { INC, AbsoluteX1 }, 6 },
  { { LSR, AbsoluteX1 }, 6 },
  { { ROL, AbsoluteX1 }, 6 },
  { { ROR, AbsoluteX1 }, 6 },

  { { ADC, AbsoluteX2 }, 4.1 },
  { { AND, AbsoluteX2 }, 4.1 },
  { { CMP, AbsoluteX2 }, 4.1 },
  { { EOR, AbsoluteX2 }, 4.1 },
  { { LDA, AbsoluteX2 }, 4.1 },
  { { LDY, AbsoluteX2 }, 4.1 },
  { { ORA, AbsoluteX2 }, 4.1 },
  { { SBC, AbsoluteX2 }, 4.1 },
  { { STA, AbsoluteX2 }, 4.1 },
  { { ASL, AbsoluteX2 }, 6 },
  { { DEC, AbsoluteX2 }, 6 },
  { { INC, AbsoluteX2 }, 6 },
  { { LSR, AbsoluteX2 }, 6 },
  { { ROL, AbsoluteX2 }, 6 },
  { { ROR, AbsoluteX2 }, 6 },

  { { ADC, AbsoluteY0 }, 4.1 },
  { { AND, AbsoluteY0 }, 4.1 },
  { { EOR, AbsoluteY0 }, 4.1 },
  { { LDA, AbsoluteY0 }, 4.1 },
  { { LDX, AbsoluteY0 }, 4.1 },
  { { ORA, AbsoluteY0 }, 4.1 },
  { { SBC, AbsoluteY0 }, 4.1 },
  { { STA, AbsoluteY0 }, 4.1 },

  { { ADC, AbsoluteY1 }, 4.1 },
  { { AND, AbsoluteY1 }, 4.1 },
  { { EOR, AbsoluteY1 }, 4.1 },
  { { LDA, AbsoluteY1 }, 4.1 },
  { { LDX, AbsoluteY1 }, 4.1 },
  { { ORA, AbsoluteY1 }, 4.1 },
  { { SBC, AbsoluteY1 }, 4.1 },
  { { STA, AbsoluteY1 }, 4.1 },

  { { ADC, AbsoluteY2 }, 4.1 },
  { { AND, AbsoluteY2 }, 4.1 },
  { { EOR, AbsoluteY2 }, 4.1 },
  { { LDA, AbsoluteY2 }, 4.1 },
  { { LDX, AbsoluteY2 }, 4.1 },
  { { ORA, AbsoluteY2 }, 4.1 },
  { { SBC, AbsoluteY2 }, 4.1 },
  { { STA, AbsoluteY2 }, 4.1 },

  { { ADC, IndirectX0 }, 6 },
  { { AND, IndirectX0 }, 6 },
  { { CMP, IndirectX0 }, 6 },
  { { EOR, IndirectX0 }, 6 },
  { { LDA, IndirectX0 }, 6 },
  { { ORA, IndirectX0 }, 6 },
  { { SBC, IndirectX0 }, 6 },
  { { STA, IndirectX0 }, 6 },

  { { ADC, IndirectX1 }, 6 },
  { { AND, IndirectX1 }, 6 },
  { { CMP, IndirectX1 }, 6 },
  { { EOR, IndirectX1 }, 6 },
  { { LDA, IndirectX1 }, 6 },
  { { ORA, IndirectX1 }, 6 },
  { { SBC, IndirectX1 }, 6 },
  { { STA, IndirectX1 }, 6 },

  { { ADC, IndirectX2 }, 6 },
  { { AND, IndirectX2 }, 6 },
  { { CMP, IndirectX2 }, 6 },
  { { EOR, IndirectX2 }, 6 },
  { { LDA, IndirectX2 }, 6 },
  { { ORA, IndirectX2 }, 6 },
  { { SBC, IndirectX2 }, 6 },
  { { STA, IndirectX2 }, 6 },

  { { ADC, IndirectX3 }, 6 },
  { { AND, IndirectX3 }, 6 },
  { { CMP, IndirectX3 }, 6 },
  { { EOR, IndirectX3 }, 6 },
  { { LDA, IndirectX3 }, 6 },
  { { ORA, IndirectX3 }, 6 },
  { { SBC, IndirectX3 }, 6 },
  { { STA, IndirectX3 }, 6 },

  { { ADC, IndirectY0 }, 5.1 },
  { { AND, IndirectY0 }, 5.1 },
  { { CMP, IndirectY0 }, 5.1 },
  { { EOR, IndirectY0 }, 5.1 },
  { { LDA, IndirectY0 }, 5.1 },
  { { ORA, IndirectY0 }, 5.1 },
  { { SBC, IndirectY0 }, 5.1 },
  { { STA, IndirectY0 }, 5.1 },

  { { ADC, IndirectY1 }, 5.1 },
  { { AND, IndirectY1 }, 5.1 },
  { { CMP, IndirectY1 }, 5.1 },
  { { EOR, IndirectY1 }, 5.1 },
  { { LDA, IndirectY1 }, 5.1 },
  { { ORA, IndirectY1 }, 5.1 },
  { { SBC, IndirectY1 }, 5.1 },
  { { STA, IndirectY1 }, 5.1 },

  { { ADC, IndirectY2 }, 5.1 },
  { { AND, IndirectY2 }, 5.1 },
  { { CMP, IndirectY2 }, 5.1 },
  { { EOR, IndirectY2 }, 5.1 },
  { { LDA, IndirectY2 }, 5.1 },
  { { ORA, IndirectY2 }, 5.1 },
  { { SBC, IndirectY2 }, 5.1 },
  { { STA, IndirectY2 }, 5.1 },

  { { ADC, IndirectY3 }, 5.1 },
  { { AND, IndirectY3 }, 5.1 },
  { { CMP, IndirectY3 }, 5.1 },
  { { EOR, IndirectY3 }, 5.1 },
  { { LDA, IndirectY3 }, 5.1 },
  { { ORA, IndirectY3 }, 5.1 },
  { { SBC, IndirectY3 }, 5.1 },
  { { STA, IndirectY3 }, 5.1 },

  { { JMP, Indirect0 }, 5 },
  { { JMP, Indirect1 }, 5 },
  { { JMP, Indirect2 }, 5 },

  { { BPL, Absolute0 }, 2.5 },
  { { BMI, Absolute0 }, 2.5 },
  { { BVC, Absolute0 }, 2.5 },
  { { BVS, Absolute0 }, 2.5 },
  { { BCC, Absolute0 }, 2.5 },
  { { BCS, Absolute0 }, 2.5 },
  { { BNE, Absolute0 }, 2.5 },
  { { BEQ, Absolute0 }, 2.5 },

  { { BPL, Absolute1 }, 2.5 },
  { { BMI, Absolute1 }, 2.5 },
  { { BVC, Absolute1 }, 2.5 },
  { { BVS, Absolute1 }, 2.5 },
  { { BCC, Absolute1 }, 2.5 },
  { { BCS, Absolute1 }, 2.5 },
  { { BNE, Absolute1 }, 2.5 },
  { { BEQ, Absolute1 }, 2.5 },

  { { BPL, Absolute2 }, 2.5 },
  { { BMI, Absolute2 }, 2.5 },
  { { BVC, Absolute2 }, 2.5 },
  { { BVS, Absolute2 }, 2.5 },
  { { BCC, Absolute2 }, 2.5 },
  { { BCS, Absolute2 }, 2.5 },
  { { BNE, Absolute2 }, 2.5 },
  { { BEQ, Absolute2 }, 2.5 },

  { { ASL_A, None }, 2 },
  { { CLC, None }, 2 },
  { { SEC, None }, 2 },
  { { CLI, None }, 2 },
  { { SEI, None }, 2 },
  { { CLV, None }, 2 },
  { { CLD, None }, 2 },
  { { SED, None }, 2 },
  { { LSR_A, None }, 2 },
  // { { NOP, None }, 2 },
  { { TAX, None }, 2 },
  { { TXA, None }, 2 },
  { { DEX, None }, 2 },
  { { INX, None }, 2 },
  { { TAY, None }, 2 },
  { { TYA, None }, 2 },
  { { DEY, None }, 2 },
  { { INY, None }, 2 },
  { { ROL_A, None }, 2 },
  { { ROR_A, None }, 2 },
  { { TXS, None }, 2 },
  { { TSX, None }, 2 },
  { { PHA, None }, 3 },
  { { PHP, None }, 3 },
  { { PLA, None }, 4 },
  { { PLP, None }, 4 },
  { { RTI, None }, 6 },
  { { RTS, None }, 6 },
};
